PUT http://localhost:8080/users/change-password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiIzMzMzIiwiaXNBZG1pbiI6ZmFsc2UsImV4cCI6MTc1NjQ1MDMyNH0.EtFM8LnD9GZg3GnHADF6rlpVGwMXaUxwiVvCClAijVc

{
    "current_password": "Newpassword",
    "new_password": "113232sssA!"
}