DELETE http://localhost:8080/users/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJhZG1pbiIsImlzQWRtaW4iOnRydWUsImV4cCI6MTc1NjQ0ODE3MX0.zbl1jvadECTkdI6DrQOBaJqd55pEsilM7abKtu-d9SY