GET http://localhost:8080/users/5
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiIiLCJpc0FkbWluIjpmYWxzZSwiZXhwIjoxNzU2MzI3NjI2fQ.2vOkQrWx4YzIDiZqaXi0sPQ7g_6AfLm1p-gwH_hDmJU