PATCH http://localhost:8080/users/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiIiLCJpc0FkbWluIjpmYWxzZSwiZXhwIjoxNzU2MjA4NTU3fQ.UvUzEh9N3IihudF_WDuwUqK0yf8bJY2qnQSnC2w7obU

{
    "username": "3333",
    "email": "user3!!!!_newemail@mail.ru"
}