PATCH http://localhost:8080/users/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiIiLCJpc0FkbWluIjpmYWxzZSwiZXhwIjoxNzU2MzMxMTAwfQ.w6TIwGCt_vZxJPJrrD16PZVK4YnAYUUSPBTyY7nNh1U

{
    "username": "user6",
    "email": "user6@gmail.com"
}